onboarding_task/Models/Users.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace onboarding_task.Models
{
    public class Users : IdentityUser
    {
        public string UserName { get; set; }

        public string Email { get; set; }
    }
}

onboarding_task/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using onboarding_task.Data;
using onboarding_task.Models;
using Task = onboarding_task.Models.Task;

namespace onboarding_task.Controllers
{
    public class TaskController : Controller
    {

        private readonly ApplicationDbContext _db;

        public TaskController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string? id)
        {
            IEnumerable<Task> obj = _db.Tasks.Where(m => m.userId ==  id);
            ViewBag.IdUser = id;
            return View(obj);
        }

        //GET
        public IActionResult Create(string? id)
        {
            Task Data = new Task
            {
                userId = (string)id
            };
            return View(Data);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("TaskName,startTime,endTime,userId")] Task obj)
        {
            if (ModelState.IsValid)
            {
                _db.Tasks.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = obj.userId });
            }
            return View(obj);
        }

        //GET 
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var FromDb = _db.Tasks.Find(id);

            if (FromDb == null)
            {
                return NotFound();
            }

            return View(FromDb);
        }

        //PUT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Task obj)
        {
            if (ModelState.IsValid)
            {
                _db.Tasks.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = obj.userId });
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var itemFromDb = _db.Tasks.Find(id);

            if (itemFromDb == null)
            {
                return NotFound();
            }

            return View(itemFromDb);
        }

        //Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Tasks.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Tasks.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index", new { id = obj.userId });

        }


    }
}

onboarding_task/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using onboarding_task.Data;
using onboarding_task.Models;

namespace onboarding_task.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private IPasswordHasher<IdentityUser> _passwordHasher;

        public UserController(UserManager<IdentityUser> userManager, IPasswordHasher<IdentityUser> passwordHash)
        {
            _userManager = userManager;
            _passwordHasher = passwordHash;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users.ToList());
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string Id, string Email, string UserName, string PhoneNumber, string Password)
        {
            var user = await _userManager.FindByIdAsync(Id);
            if (user != null)
            {
                if (!string.IsNullOrEmpty(Email))
                    user.Email = Email;
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                if (!string.IsNullOrEmpty(Password))
                    user.PasswordHash = _passwordHasher.HashPassword(user, Password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");


                if (!string.IsNullOrEmpty(Email))
                {
                    user.UserName = UserName;
                    user.PhoneNumber = PhoneNumber;
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                        return View(user);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    View(user);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }
    }
}

onboarding_task/Views/User/Edit.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser

<h1>Edit User</h1>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input asp-for="Id" hidden />
            <div class="form-group">
                <label asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" />
            </div>

            <br />
            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>

    </div>
</div>

onboarding_task/Views/User/Index.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityUser>
@{
    ViewData["Title"] = "User";
}

<div class="container">
    <div class="row">
        <div class="col-4">
            <h2>Daftar User</h2>
        </div>
        <div class="col-4">
            <a asp-controller="User" asp-action="Create" class="btn btn-primary">
                Tambah User
            </a>
        </div>
    </div>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    User Name
                </th>
                <th>
                    Email
                </th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        @obj.UserName
                    </td>
                    <td>
                        @obj.Email
                    </td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a asp-controller="Task" asp-action="Index" asp-route-id="@obj.Id" class="btn btn-primary">Detail</a>
                            <a asp-controller="User" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-warning">Edit</a>
                            <form asp-controller="User" asp-action="Delete" asp-route-id="@obj.Id" method="post">
                                <button type="submit" class="btn btn-danger">
                                    Delete
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>